USE pad;

INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('103', '1', 'KEY_SCREEN_CREATE_LABEL', 'Create');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('104', '2', 'KEY_SCREEN_CREATE_LABEL', 'Créer');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('105', '1', 'KEY_SCREEN_CREATE_MISSION_LABEL', 'Create Mission');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('106', '2', 'KEY_SCREEN_CREATE_MISSION_LABEL', 'Créer une mission');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('107', '1', 'KEY_SCREEN_MISSION_DETAIL_LABEL', 'Mission Details');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('108', '2', 'KEY_SCREEN_MISSION_DETAIL_LABEL', 'Détails de la mission');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('109', '1', 'KEY_SCREEN_OPERATOR_LABEL', 'Operator');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('110', '2', 'KEY_SCREEN_OPERATOR_LABEL', 'Opérateur');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('111', '1', 'KEY_SCREEN_CONSIGNMENT_NUMBER_LABEL', 'Consignment Number');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('112', '2', 'KEY_SCREEN_CONSIGNMENT_NUMBER_LABEL', 'Numéro de lot');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('113', '1', 'KEY_SCREEN_START_DATE_LABEL', 'Start Date');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('114', '2', 'KEY_SCREEN_START_DATE_LABEL', 'Date de début');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('115', '1', 'KEY_SCREEN_END_DATE_LABEL', 'End Date');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('116', '2', 'KEY_SCREEN_END_DATE_LABEL', 'Date de fin');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('117', '1', 'KEY_SCREEN_NUMBER_TRIPS_LABEL', 'Number of Trips');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('118', '2', 'KEY_SCREEN_NUMBER_TRIPS_LABEL', 'Nombre de voyages');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('119', '1', 'KEY_SCREEN_COLLECTION_LABEL', 'Collection');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('120', '2', 'KEY_SCREEN_COLLECTION_LABEL', 'Collection');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('121', '1', 'KEY_SCREEN_DELIVERY_LABEL', 'Delivery');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('122', '2', 'KEY_SCREEN_DELIVERY_LABEL', 'Livraison');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('123', '1', 'KEY_SCREEN_LOADED_LABEL', 'Loaded');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('124', '2', 'KEY_SCREEN_LOADED_LABEL', 'Chargé');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('125', '1', 'KEY_SCREEN_EMPTY_LABEL', 'Empty');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('126', '2', 'KEY_SCREEN_EMPTY_LABEL', 'Vide');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('127', '1', 'KEY_SCREEN_NEXT_LABEL', 'Next');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('128', '2', 'KEY_SCREEN_NEXT_LABEL', 'Suivant');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('129', '1', 'KEY_SCREEN_VEHICLES_DRIVERS_LABEL', 'Vehicles and Drivers');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('130', '2', 'KEY_SCREEN_VEHICLES_DRIVERS_LABEL', 'Véhicules et chauffeurs');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('131', '1', 'KEY_SCREEN_CHOOSE_VEHICLE_LABEL', 'Choose a Vehicle');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('132', '2', 'KEY_SCREEN_CHOOSE_VEHICLE_LABEL', 'Choisissez un véhicule');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('133', '1', 'KEY_SCREEN_CHOOSE_DRIVER_LABEL', 'Choose a Driver');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('134', '2', 'KEY_SCREEN_CHOOSE_DRIVER_LABEL', 'Choisissez un pilote');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('135', '1', 'KEY_SCREEN_NUMBER_PASSENGERS_LABEL', 'Number of Passengers');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('136', '2', 'KEY_SCREEN_NUMBER_PASSENGERS_LABEL', 'Nombre de passagers');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('137', '1', 'KEY_SCREEN_ADD_LABEL', 'Add');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('138', '2', 'KEY_SCREEN_ADD_LABEL', 'Ajouter');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('139', '1', 'KEY_SCREEN_VEHICLE_LABEL', 'Vehicle');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('140', '2', 'KEY_SCREEN_VEHICLE_LABEL', 'Véhicule');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('141', '1', 'KEY_SCREEN_DRIVER_LABEL', 'Driver');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('142', '2', 'KEY_SCREEN_DRIVER_LABEL', 'Chauffeur');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('143', '1', 'KEY_SCREEN_PASSENGERS_LABEL', 'Passengers');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('144', '2', 'KEY_SCREEN_PASSENGERS_LABEL', 'Les passagers');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('145', '1', 'KEY_SCREEN_REVIEW_SUBMIT_LABEL', 'Review and Submit');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('146', '2', 'KEY_SCREEN_REVIEW_SUBMIT_LABEL', 'Examiner et Soumettre');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('147', '1', 'KEY_SCREEN_REVIEW_SUBMIT_MISSION_MESSAGE', 'Please review the details carefully. If you wish to modify it, please select the appropriate step');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('148', '2', 'KEY_SCREEN_REVIEW_SUBMIT_MISSION_MESSAGE', 'S\'il vous plaît examiner les détails attentivement. Si vous souhaitez le modifier, veuillez sélectionner l’étape appropriée.');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('149', '1', 'KEY_SCREEN_TRIP_TYPE_LABEL', 'Trip Type');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('150', '2', 'KEY_SCREEN_TRIP_TYPE_LABEL', 'Type de voyage');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('151', '1', 'KEY_SCREEN_CONTAINER_TYPE_LABEL', 'Container Type');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('152', '2', 'KEY_SCREEN_CONTAINER_TYPE_LABEL', 'Type de conteneur');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('153', '1', 'KEY_SCREEN_SELECT_OPERATOR_MESSAGE', 'Please select Operator');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('154', '2', 'KEY_SCREEN_SELECT_OPERATOR_MESSAGE', 'Veuillez sélectionner l\'opérateur');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('155', '1', 'KEY_SCREEN_ENTER_CONSIGNMENT_NUMBER_MESSAGE', 'Please enter Consignment Number');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('156', '2', 'KEY_SCREEN_ENTER_CONSIGNMENT_NUMBER_MESSAGE', 'Veuillez entrer le numéro de lot');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('157', '1', 'KEY_SCREEN_ENTER_START_DATE_MESSAGE', 'Please enter Start Date');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('158', '2', 'KEY_SCREEN_ENTER_START_DATE_MESSAGE', 'S\'il vous plaît entrer la date de début');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('159', '1', 'KEY_SCREEN_ENTER_END_DATE_MESSAGE', 'Please enter End Date');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('160', '2', 'KEY_SCREEN_ENTER_END_DATE_MESSAGE', 'S\'il vous plaît entrer la date de fin');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('161', '1', 'KEY_SCREEN_REFRESH_LABEL', 'Refresh');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('162', '2', 'KEY_SCREEN_REFRESH_LABEL', 'Rafraîchir');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('163', '1', 'KEY_SCREEN_DETAILS_LABEL', 'Details');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('164', '2', 'KEY_SCREEN_DETAILS_LABEL', 'Détails');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('165', '1', 'KEY_SCREEN_NO_MISSION_RETURNED_MESSAGE', 'No missions returned');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('166', '2', 'KEY_SCREEN_NO_MISSION_RETURNED_MESSAGE', 'Aucune mission retournée');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('167', '1', 'KEY_SCREEN_FIRST_NAME_LABEL', 'First Name');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('168', '2', 'KEY_SCREEN_FIRST_NAME_LABEL', 'Prénom');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('169', '1', 'KEY_SCREEN_LAST_NAME_LABEL', 'Last Name');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('170', '2', 'KEY_SCREEN_LAST_NAME_LABEL', 'Nom de famille');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('171', '1', 'KEY_SCREEN_MOBILE_NUMBER_LABEL', 'Mobile Number');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('172', '2', 'KEY_SCREEN_MOBILE_NUMBER_LABEL', 'Numéro de portable');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('173', '1', 'KEY_SCREEN_NATIONALITY_LABEL', 'Nationality');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('174', '2', 'KEY_SCREEN_NATIONALITY_LABEL', 'Nationalité');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('175', '1', 'KEY_SCREEN_LICENCE_NUMBER_LABEL', 'Licence Number');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('176', '2', 'KEY_SCREEN_LICENCE_NUMBER_LABEL', 'Numéro de licence');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('177', '1', 'KEY_SCREEN_NO_DRIVER_RETURNED_MESSAGE', 'No drivers returned');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('178', '2', 'KEY_SCREEN_NO_DRIVER_RETURNED_MESSAGE', 'Aucun chauffeur retourné');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('179', '1', 'KEY_SCREEN_ADD_DRIVER_LABEL', 'Add Driver');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('180', '2', 'KEY_SCREEN_ADD_DRIVER_LABEL', 'Ajouter un pilote');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('181', '1', 'KEY_SCREEN_ENTER_FIRST_NAME_MESSAGE', 'Please enter First Name');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('182', '2', 'KEY_SCREEN_ENTER_FIRST_NAME_MESSAGE', 'S\'il vous plaît entrer Prénom');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('183', '1', 'KEY_SCREEN_ENTER_LAST_NAME_MESSAGE', 'Please enter Last Name');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('184', '2', 'KEY_SCREEN_ENTER_LAST_NAME_MESSAGE', 'Veuillez entrer le nom de famille');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('185', '1', 'KEY_SCREEN_ENTER_EMAIL_MESSAGE', 'Please enter Email');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('186', '2', 'KEY_SCREEN_ENTER_EMAIL_MESSAGE', 'S\'il vous plaît entrer Email');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('187', '1', 'KEY_SCREEN_ENTER_VALID_MOBILE_NUMBER_MESSAGE', 'Please enter valid Mobile Number');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('188', '2', 'KEY_SCREEN_ENTER_VALID_MOBILE_NUMBER_MESSAGE', 'Veuillez entrer un numéro de téléphone valide');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('189', '1', 'KEY_SCREEN_SELECT_NATIONALITY_MESSAGE', 'Please select Nationality');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('190', '2', 'KEY_SCREEN_SELECT_NATIONALITY_MESSAGE', 'Veuillez sélectionner une nationalité');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('191', '1', 'KEY_SCREEN_ENTER_LICENCE_NUMBER_MESSAGE', 'Please enter Licence Number');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('192', '2', 'KEY_SCREEN_ENTER_LICENCE_NUMBER_MESSAGE', 'S\'il vous plaît entrer le numéro de licence');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('193', '1', 'KEY_NAVBAR_PARKING', 'Parking');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('194', '2', 'KEY_NAVBAR_PARKING', 'Parking');

