USE pad;

CREATE TABLE pad.`anpr_entry_log` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`is_processed` int(11) NOT NULL,
`date_created` datetime NOT NULL,
`date_scheduled` datetime NOT NULL,
`date_processed` datetime DEFAULT NULL,
`entry_log_id` int(11) NOT NULL,
`lane_id` int(11) NULL,
`plate_number` varchar(32) NOT NULL,
`recognized_plate_number` varchar(32) NOT NULL,
`parking_permission_id` int(11) NULL,
`notes` varchar(64) NOT NULL,
`timestamp` varchar(32) NOT NULL,
`entry_event_type_id` int(11) NOT NULL,
`entering_direction_id` tinyint(1) NOT NULL,
`tenant_card_id` int(11) NULL,
`car_id` int(11) NULL,
`tenant_person_id` int(11) NULL,
`tenant_company_id` int(11) NULL,
`image_path` varchar(64) NOT NULL,
`entering_event_id` int(11) NULL,
`blacklist_id` int(11) NULL,
`user_id` int(11) NULL,
`zone_id_from` int(11) NOT NULL,
`zone_from` varchar(32) NOT NULL,
`zone_id_to` int(11) NOT NULL,
`zone_to` varchar(32) NOT NULL,
`applicants` varchar(32) NOT NULL,
`user_name` varchar(32) NOT NULL,
`lane_name` varchar(32) NOT NULL,
`company_name` varchar(32) NOT NULL,
`person_name` varchar(32) NOT NULL,
`car_plate_number` varchar(32) NOT NULL,
`card_number` varchar(32) NOT NULL,
`entering_event_name` varchar(32) NOT NULL,
`entering_direction_name` varchar(32) NOT NULL,
`area_code_name` varchar(32) NOT NULL,
PRIMARY KEY (`id`),
KEY `date_scheduled_ik` (`date_scheduled`),
KEY `entry_event_type_id_ik` (`entry_event_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE pad.`anpr_entry_scheduler` (
`id` int(11) NOT NULL,
`is_processed` int(11) NOT NULL,
`date_created` datetime NOT NULL,
`date_scheduled` datetime NOT NULL,
`date_processed` datetime DEFAULT NULL,
`entry_log_id` int(11) NOT NULL,
`lane_id` int(11) NULL,
`plate_number` varchar(32) NOT NULL,
`recognized_plate_number` varchar(32) NOT NULL,
`parking_permission_id` int(11) NULL,
`notes` varchar(64) NOT NULL,
`timestamp` varchar(32) NOT NULL,
`entry_event_type_id` int(11) NOT NULL,
`entering_direction_id` tinyint(1) NOT NULL,
`tenant_card_id` int(11) NULL,
`car_id` int(11) NULL,
`tenant_person_id` int(11) NULL,
`tenant_company_id` int(11) NULL,
`image_path` varchar(64) NOT NULL,
`entering_event_id` int(11) NULL,
`blacklist_id` int(11) NULL,
`user_id` int(11) NULL,
`zone_id_from` int(11) NOT NULL,
`zone_from` varchar(32) NOT NULL,
`zone_id_to` int(11) NOT NULL,
`zone_to` varchar(32) NOT NULL,
`applicants` varchar(32) NOT NULL,
`user_name` varchar(32) NOT NULL,
`lane_name` varchar(32) NOT NULL,
`company_name` varchar(32) NOT NULL,
`person_name` varchar(32) NOT NULL,
`car_plate_number` varchar(32) NOT NULL,
`card_number` varchar(32) NOT NULL,
`entering_event_name` varchar(32) NOT NULL,
`entering_direction_name` varchar(32) NOT NULL,
`area_code_name` varchar(32) NOT NULL,
PRIMARY KEY (`id`),
KEY `date_scheduled_ik` (`date_scheduled`),
KEY `entry_event_type_id_ik` (`entry_event_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

