USE pad;
ALTER TABLE `pad`.`system_parameters` 
DROP COLUMN `max_amount_hold`;

INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('1157', '1', 'KEY_SCREEN_PARKING_EXIT_MSG_AUTH_EXIT', 'Advise the driver they are authorised to proceed to the port entry right away');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('1158', '2', 'KEY_SCREEN_PARKING_EXIT_MSG_AUTH_EXIT', 'Aviser le conducteur qu\'il est autorisé à se rendre immédiatement à l\'entrée du port');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('1159', '1', 'KEY_SCREEN_PARKING_EXIT_MSG_PREMATURE_EXIT', 'Advise the driver they have not been authorised to enter the port at this time. A fine will be applied to the driver if they try to enter the port. They need to make their way back to the parking area to await approval to enter the port. They must be back in the parking area within the next 45 minutes or an additional fee will apply');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('1160', '2', 'KEY_SCREEN_PARKING_EXIT_MSG_PREMATURE_EXIT', 'Informez le conducteur qu\'il n\'a pas été autorisé à entrer dans le port pour le moment. Une amende sera appliquée au pilote s’il tente d’entrer dans le port. Ils doivent regagner l\'aire de stationnement pour attendre l\'autorisation d\'entrer dans le port. Ils doivent être de retour dans l\'aire de stationnement dans les 45 prochaines minutes, sans quoi des frais supplémentaires seront appliqués');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('1161', '1', 'KEY_SCREEN_PARKING_EXIT_MSG_EXIT_ONLY', 'Advise the driver they have not been authorised to enter the port at this time. A fine will be applied to the driver if they try to enter the port');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('1162', '2', 'KEY_SCREEN_PARKING_EXIT_MSG_EXIT_ONLY', 'Informez le conducteur qu\'il n\'a pas été autorisé à entrer dans le port pour le moment. Une amende sera appliquée au conducteur s\'il tente d\'entrer dans le port');
