USE pad;

ALTER TABLE `pad`.`accounts`
ADD COLUMN `status` INT(11) NOT NULL AFTER `type`;

UPDATE pad.accounts SET status = 2 WHERE id > 0;

UPDATE `pad`.`email_templates` SET `message`='<table width=\"600\" cellspacing=\"0\" border=\"0\" cellpadding=\"0\" style=\"width:100%;padding:32px 50px 32px;border-left:1px solid #e8e8e9;border-right:1px solid #e8e8e9\"><tbody><tr><td><p style=\"font-family:\'Helvetica Neue\';font-size:26px;font-weight:normal;color:#545457;margin:1em 0\">Hello ${operatorName},</p></td></tr><tr><td><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"width:100%\"><tbody><tr><td><p style=\"font-family:Helvetica;font-size:16px;color:#545457;line-height:22px;margin-bottom:1.3em\">We are delighted to confirm your registration with Port Access Dakar! Please note, your account will be activated in the next 24 hours. Please click on the link below to login.\n                                                    \n                                                    </p></td></tr><tr><td><p style=\"font-family:Helvetica;font-size:16px;color:#545457;line-height:22px;margin-bottom:1.3em\">Please \n                                                        \n                                                            \n                                                      \n                                                  \n                                                                                                    \n                                    \n                  <a href=\"${loginPageUrl}\"><strong>click here</strong></a> to login!\n                                                        \n                                                          \n                                                    \n                                                \n                                                                                                \n                                \n                </p></td></tr><tr><td><p style=\"font-family:Helvetica;font-size:16px;color:#707074;line-height:22px;margin-bottom:1em\">\n                                    Kind Regards,\n                                                          \n                                                          \n                                                          \n                                                            \n                                                      \n                                                  \n                                                                                                    \n                                    \n                  <br><strong>PAD Support Team</strong></p></td></tr></tbody></table>' WHERE `id`='3';

UPDATE `pad`.`email_templates` SET `message`='<table width=\"600\" cellspacing=\"0\" border=\"0\" cellpadding=\"0\" style=\"width:100%;padding:32px 50px 32px;border-left:1px solid #e8e8e9;border-right:1px solid #e8e8e9\"><tbody><tr><td><p style=\"font-family:\'Helvetica Neue\';font-size:26px;font-weight:normal;color:#545457;margin:1em 0\">Bonjour ${operatorName},</p></td></tr><tr><td><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"width:100%\"><tbody><tr><td><p style=\"font-family:Helvetica;font-size:16px;color:#545457;line-height:22px;margin-bottom:1.3em\">Nous sommes ravis de confirmer votre inscription auprès de Port Access Dakar! Veuillez noter que votre compte sera activé dans les prochaines 24 heures. Veuillez cliquer sur le lien ci-dessous pour vous connecter.\n                     </p></td></tr><tr><td><p style=\"font-family:Helvetica;font-size:16px;color:#545457;line-height:22px;margin-bottom:1.3em\">Please \n                        \n                  <a href=\"${loginPageUrl}\"><strong>Cliquez ici</strong></a> pour vous identifier!\n                     \n                </p></td></tr><tr><td><p style=\"font-family:Helvetica;font-size:16px;color:#707074;line-height:22px;margin-bottom:1em\">\n                        Sincères amitiés,\n                        \n                  <br><strong>PAD Support Team</strong></p></td></tr></tbody></table>' WHERE `id`='6';

INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('589', '1', 'KEY_SCREEN_ACCOUNT_PENDING_ACTIVATION_MESSAGE', 'Account is not yet activated');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('590', '2', 'KEY_SCREEN_ACCOUNT_PENDING_ACTIVATION_MESSAGE', 'Le compte n\'est pas encore activé');

INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('591', '1', 'KEY_SCREEN_NO_ACCOUNT_RETURNED_MESSAGE', 'No accounts returned');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('592', '2', 'KEY_SCREEN_NO_ACCOUNT_RETURNED_MESSAGE', 'Aucun compte retourné');

INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('593', '1', 'KEY_SCREEN_ACCOUNT_PENDING_ACTIVATION_LABEL', 'Activation Pending');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('594', '2', 'KEY_SCREEN_ACCOUNT_PENDING_ACTIVATION_LABEL', 'Activation en attente');