USE pad;

INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('197', '1', 'KEY_SCREEN_OPERATORS_LABEL', 'Operators');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('198', '2', 'KEY_SCREEN_OPERATORS_LABEL', 'Les opérateurs');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('199', '1', 'KEY_SCREEN_DATE_LAST_LOGIN_LABEL', 'Date Last Login');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('200', '2', 'KEY_SCREEN_DATE_LAST_LOGIN_LABEL', 'Date de dernière connexion');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('201', '1', 'KEY_SCREEN_DATE_CREATED_LABEL', 'Date Created');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('202', '2', 'KEY_SCREEN_DATE_CREATED_LABEL', 'date créée');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('203', '1', 'KEY_SCREEN_IS_ACTIVE_LABEL', 'Is active');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('204', '2', 'KEY_SCREEN_IS_ACTIVE_LABEL', 'C\'est actif');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('205', '1', 'KEY_SCREEN_ADMIN_UPPER_LABEL', 'ADMIN');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('206', '2', 'KEY_SCREEN_ADMIN_UPPER_LABEL', 'ADMIN');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('207', '1', 'KEY_SCREEN_OPERATOR_UPPER_LABEL', 'OPERATOR');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('208', '2', 'KEY_SCREEN_OPERATOR_UPPER_LABEL', 'OPÉRATEUR');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('209', '1', 'KEY_SCREEN_REGISTERED_UPPER_LABEL', 'REGISTERED');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('210', '2', 'KEY_SCREEN_REGISTERED_UPPER_LABEL', 'INSCRIT');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('211', '1', 'KEY_SCREEN_UNREGISTERED_UPPER_LABEL', 'UNREGISTERED');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('212', '2', 'KEY_SCREEN_UNREGISTERED_UPPER_LABEL', 'NON-INSCRIT');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('213', '1', 'KEY_SCREEN_NO_OPERATOR_RETURNED_MESSAGE', 'No Operators returned');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('214', '2', 'KEY_SCREEN_NO_OPERATOR_RETURNED_MESSAGE', 'Aucun opérateur retourné');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('215', '1', 'KEY_SCREEN_DELETE_CONFIRMATION_LABEL', 'Delete Confirmation');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('216', '2', 'KEY_SCREEN_DELETE_CONFIRMATION_LABEL', 'Supprimer la confirmation');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('217', '1', 'KEY_SCREEN_DELETE_CONFIRMATION_QUESTION', 'Are you sure you want to delete the operator');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('218', '2', 'KEY_SCREEN_DELETE_CONFIRMATION_QUESTION', 'Êtes-vous sûr de vouloir supprimer l\'opérateur');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('219', '1', 'KEY_SCREEN_YES_LABEL', 'Yes');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('220', '2', 'KEY_SCREEN_YES_LABEL', 'Oui');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('221', '1', 'KEY_SCREEN_NO_LABEL', 'No');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('222', '2', 'KEY_SCREEN_NO_LABEL', 'Non');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('223', '1', 'KEY_SCREEN_OPERATOR_ACTIVITY_LOG_LABEL', 'Operator Activity Log');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('224', '2', 'KEY_SCREEN_OPERATOR_ACTIVITY_LOG_LABEL', 'Journal d\'activité de l\'opérateur');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('225', '1', 'KEY_SCREEN_FILTER_LABEL', 'Filter');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('226', '2', 'KEY_SCREEN_FILTER_LABEL', 'Filtre');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('227', '1', 'KEY_SCREEN_ACTIVITY_LABEL', 'Activity');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('228', '2', 'KEY_SCREEN_ACTIVITY_LABEL', 'Activité');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('229', '1', 'KEY_SCREEN_ADD_OPERATOR_LABEL', 'Add Operator');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('230', '2', 'KEY_SCREEN_ADD_OPERATOR_LABEL', 'Ajouter un opérateur');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('231', '1', 'KEY_SCREEN_UPDATE_OPERATOR_LABEL', 'Update Operator');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('232', '2', 'KEY_SCREEN_UPDATE_OPERATOR_LABEL', 'Opérateur de mise à jour');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('233', '1', 'KEY_SCREEN_ACTIVE_INACTIVE_OPERATOR_LABEL', 'Active/Inactive Operator');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('234', '2', 'KEY_SCREEN_ACTIVE_INACTIVE_OPERATOR_LABEL', 'Opérateur Actif / Inactif');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('235', '1', 'KEY_SCREEN_SEND_SETUP_PASSWORD_LABEL', 'Send Password Set Up');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('236', '2', 'KEY_SCREEN_SEND_SETUP_PASSWORD_LABEL', 'Envoyer le mot de passe configuré');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('237', '1', 'KEY_SCREEN_DELETE_OPERATOR_LABEL', 'Delete Operator');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('238', '2', 'KEY_SCREEN_DELETE_OPERATOR_LABEL', 'Supprimer l\'opérateur');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('239', '1', 'KEY_SCREEN_DATE_FROM_LABEL', 'Date From');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('240', '2', 'KEY_SCREEN_DATE_FROM_LABEL', 'Dater de');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('241', '1', 'KEY_SCREEN_DATE_TO_LABEL', 'To');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('242', '2', 'KEY_SCREEN_DATE_TO_LABEL', 'à');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('243', '1', 'KEY_SCREEN_SEARCH_LABEL', 'Search');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('244', '2', 'KEY_SCREEN_SEARCH_LABEL', 'Chercher');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('245', '1', 'KEY_SCREEN_CLEAR_LABEL', 'Clear');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('246', '2', 'KEY_SCREEN_CLEAR_LABEL', 'Clair');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('247', '1', 'KEY_SCREEN_DATE_TIME_LABEL', 'Date Time');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('248', '2', 'KEY_SCREEN_DATE_TIME_LABEL', 'Date heure');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('249', '1', 'KEY_SCREEN_NO_ACTIVITY_RETURNED_MESSAGE', 'No activities returned');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('250', '2', 'KEY_SCREEN_NO_ACTIVITY_RETURNED_MESSAGE', 'Aucune activité retournée');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('251', '1', 'KEY_SCREEN_ROLE_LABEL', 'Role');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('252', '2', 'KEY_SCREEN_ROLE_LABEL', 'Rôle');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('253', '1', 'KEY_SCREEN_CONFIRM_EMAIL_LABEL', 'Confirm Email');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('254', '2', 'KEY_SCREEN_CONFIRM_EMAIL_LABEL', 'Confirmez votre e-mail');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('255', '1', 'KEY_SCREEN_COUNTRY_REGISTRATION_LABEL', 'Country of Registration');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('256', '2', 'KEY_SCREEN_COUNTRY_REGISTRATION_LABEL', 'Pays d\'enregistrement');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('257', '1', 'KEY_SCREEN_REGISTRATION_NUMBER_LABEL', 'Registration Number');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('258', '2', 'KEY_SCREEN_REGISTRATION_NUMBER_LABEL', 'Numéro d\'enregistrement');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('259', '1', 'KEY_SCREEN_TYPE_LABEL', 'Type');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('260', '2', 'KEY_SCREEN_TYPE_LABEL', 'Type');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('261', '1', 'KEY_SCREEN_MAKE_LABEL', 'Make');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('262', '2', 'KEY_SCREEN_MAKE_LABEL', 'Faire');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('263', '1', 'KEY_SCREEN_MODEL_LABEL', 'Model');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('264', '2', 'KEY_SCREEN_MODEL_LABEL', 'Modèle');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('265', '1', 'KEY_SCREEN_COLOR_LABEL', 'Color');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('266', '2', 'KEY_SCREEN_COLOR_LABEL', 'Couleur');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('267', '1', 'KEY_SCREEN_NUMBER_AXELS_LABEL', 'Number of Axels');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('268', '2', 'KEY_SCREEN_NUMBER_AXELS_LABEL', 'Nombre d\'essieux');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('269', '1', 'KEY_SCREEN_NO_VEHICLE_RETURNED_MESSAGE', 'No vehicles returned');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('270', '2', 'KEY_SCREEN_NO_VEHICLE_RETURNED_MESSAGE', 'Aucun véhicule retourné');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('271', '1', 'KEY_SCREEN_ADD_VEHICLE_LABEL', 'Add Vehicle');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('272', '2', 'KEY_SCREEN_ADD_VEHICLE_LABEL', 'Ajouter un véhicule');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('273', '1', 'KEY_SCREEN_NEW_SEARCH_LABEL', 'New Search');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('274', '2', 'KEY_SCREEN_NEW_SEARCH_LABEL', 'Nouvelle recherche');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('275', '1', 'KEY_SCREEN_VEHICLE_REGISTRATION_NUMBER_LABEL', 'Vehicle Registration Number');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('276', '2', 'KEY_SCREEN_VEHICLE_REGISTRATION_NUMBER_LABEL', 'Numéro d\'immatriculation du véhicule');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('277', '1', 'KEY_SCREEN_VEHICLE_DETAIL_LABEL', 'Vehicle Details');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('278', '2', 'KEY_SCREEN_VEHICLE_DETAIL_LABEL', 'Les détails du véhicule');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('279', '1', 'KEY_SCREEN_TRIPS_LABEL', 'Trips');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('280', '2', 'KEY_SCREEN_TRIPS_LABEL', 'Voyages');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('281', '1', 'KEY_SCREEN_BAE_NUMBER_LABEL', 'BAE Number');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('282', '2', 'KEY_SCREEN_BAE_NUMBER_LABEL', 'Numéro BAE');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('283', '1', 'KEY_SCREEN_VEHICLE_NAME_LABEL', 'Vehicle Name');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('284', '2', 'KEY_SCREEN_VEHICLE_NAME_LABEL', 'Nom du véhicule');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('285', '1', 'KEY_SCREEN_DRIVER_NAME_LABEL', 'Driver Name');
INSERT INTO `pad`.`language_keys` (`id`, `language_id`, `translate_key`, `translate_value`) VALUES ('286', '2', 'KEY_SCREEN_DRIVER_NAME_LABEL', 'Nom du conducteur');
