USE pad;

ALTER TABLE `pad`.`missions`
    ADD COLUMN `transporter_comments` VARCHAR(8192) NOT NULL AFTER `reference_number`;

UPDATE `pad`.`email_templates`
SET `message` = '<table width=\"600\" cellspacing=\"0\" border=\"0\" cellpadding=\"0\" style=\"width:100%;padding:32px 50px 32px;border-left:1px solid #e8e8e9;border-right:1px solid #e8e8e9\"><tbody><tr><td><p style=\"font-family:\'Helvetica Neue\';font-size:26px;font-weight:normal;color:#545457;margin:1em 0\">Hello ${accountName},</p></td></tr><tr><td><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"width:100%\"><tbody><tr><td><p style=\"font-family:Helvetica;font-size:16px;color:#545457;line-height:22px;margin-bottom:1.3em\">Please note, a new mission has been created on your account. Please \r                   \r                   <a href=\"${loginPageUrl}\"><strong>click here</strong></a> to login and book the trip.\r                 \r                 </p></td></tr><tr><td><table style=\"font-family:Helvetica;font-size:16px;color:#545457;\"><tr><td>Port Operator</td><td>${portOperator}</td></tr><tr><td>BAD Number</td><td>${referenceNumber}</td></tr><tr><td>Transaction Type</td><td>${transactionType}</td></tr><tr><td>Comments</td><td>${transporterComments}</td></tr><tr><td>Start Date</td><td>${startDate}</td></tr><tr><td>End Date</td><td>${endDate}</td></tr></table></td></tr><tr><td><p style=\"font-family:Helvetica;font-size:16px;color:#707074;line-height:22px;margin-bottom:1em\">Kind Regards,\r                   \r                   <br><strong>AGS Support Team</strong><br>https://www.agsparking.com\r                     \r                     </p></td></tr></tbody></table></td></tr></tbody></table>'
WHERE (`id` = '15');
UPDATE `pad`.`email_templates`
SET `message` = '<table width=\"600\" cellspacing=\"0\" border=\"0\" cellpadding=\"0\" style=\"width:100%;padding:32px 50px 32px;border-left:1px solid #e8e8e9;border-right:1px solid #e8e8e9\"><tbody><tr><td><p style=\"font-family:\'Helvetica Neue\';font-size:26px;font-weight:normal;color:#545457;margin:1em 0\">Bonjour ${accountName},</p></td></tr><tr><td><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"width:100%\"><tbody><tr><td><p style=\"font-family:Helvetica;font-size:16px;color:#545457;line-height:22px;margin-bottom:1.3em\">Veuillez noter qu\'une nouvelle mission a été créée sur votre compte. S\'il vous plaît \r                   <a href=\"${loginPageUrl}\"><strong>cliquez ici</strong></a> pour vous connecter et réserver le voyage.\r                 </p></td></tr><tr><td><table style=\"font-family:Helvetica;font-size:16px;color:#545457;\"><tr><td>Opérateur Portuaire</td><td>${portOperator}</td></tr><tr><td>Nombre de BAD</td><td>${referenceNumber}</td></tr><tr><td>Type de transaction</td><td>${transactionType}</td></tr><tr><td>Commentaires</td><td>${transporterComments}</td></tr><tr><td>Date de début</td><td>${startDate}</td></tr><tr><td>Date de fin</td><td>${endDate}</td></tr></table></td></tr><tr><td><p style=\"font-family:Helvetica;font-size:16px;color:#707074;line-height:22px;margin-bottom:1em\">\r  Sincères amitiés,\r                   <br><strong>AGS Support Team</strong><br>https://www.agsparking.com\r                     </p></td></tr></tbody></table></td></tr></tbody></table>'
WHERE (`id` = '16');


